plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions: 
  "@nestjs/apollo@*":
    dependencies:
      graphql: "^15.3.0"
  "@nestjs/serve-static@*":
    dependencies:
      express: "^4.17.3"
