name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true

  jobs:
    deploy:
      runs-on: [self-hosted, deployment]
      steps:  
        - name: Log deployment
          run: echo Deploying on ${{github.event.input.environment}} 
