name: Run e2e tests

on:
  workflow_run:
    workflows: [CI build]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Pipenv
        run: pip install pipenv

      - name: Run tests
        run: |
          yarn install 
          yarn workspace auto-nlp-ui exec cypress run --spec cypress/integration/e2e.spec.js

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: E2E Tests            # Name of the check run which will be created
          path: '**/test-results.xml'        # Path to test results
          reporter: jest-junit        # Format of test results
