name: release

# RunEntity the workflow when a Pull Request is opened or when changes are pushed to master
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # RunEntity the steps below with the following versions of Node.js
        node-version: [ 14.x ]
        python-version: [ 3.9 ]

    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      #Setup python and pipenv
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: pip install pipenv

      # Set yarn version
      - name: Set up yarn
        run: yarn set version 3.x

      # Install package dependencies
      - name: Install
        run: yarn install --immutable

      # RunEntity tests
      - name: Test
        run: yarn workspaces foreach -v run --inspect-brk test --runInBand # TODO: There might be an "intelligent" solution to run tests for changed+change-affected workspaces

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '**/junit.xml'        # Path to test results
          reporter: jest-junit        # Format of test results

  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Fetch the latest commit
      - name: Checkout
        uses: actions/checkout@v2

      # Setup Node.js using the appropriate version
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Pipenv
        run: pip install pipenv

      - name: Release
        run: |
          yarn install 
          yarn workspace auto-nlp-core exec npx semantic-release -e semantic-release-monorepo
          yarn workspaces foreach -v exec npx semantic-release -e semantic-release-monorepo 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
